### ISSUE TITLE
intensity matrix of bladder_cancer data not readable

### ISSUE THREAD

**Issue by Seveler** [Vitek-Lab/mi-CNN_MSI#2]
Dear Dan Guo,

I am currently working on a paper and would like to your the bladder_cancer dataset you provide here. However, I was unable to read the intensity matrix of your data. Accessing the feature data, x and y coordinates and also the labels works perfectly. But I am unable to read the intensity matrix ("imageData" as class `MSContinuousImagingSpectraList`) with Cardinal 3.6. It is also not possible to convert it in an array or any other format. 
I assume it would work with Cardinal 2.x , but installing it did not work because some libraries depend on newer versions on R.

Would it be possible to provide the intensity matrix in a different file format which is easy to read (e.g. csv, imzML, npy, ...)?

Kind regards

**Comment by kuwisdelu** [comment]
Please try calling `updateObject()` on the `MSContinuousImagingExperiment` object.

If that does not work, the old `@imageData` slot for that class is just a fancy wrapper on a regular matrix.

You should be able to extract the intensity matrix using `obj@imageData$data[[1]]` on the `MSContinuousImagingExperiment` or just `obj$data[[1]]` on the `MSContinuousImagingSpectraList`.

Note that some Cardinal methods that Dan used might need some adjustment to work in 3.6 due to the changes since this work.

The base strategy of multiple instance learning is available in Cardinal 3.6 directly via `matter::mi_learn()` or by setting the `bags` argument in `PLS()`, `OPLS()`, or `spatialShrunkenCentroids()`.

(The CNN-based method is not provided due to the tensorflow requirements.)

-Kylie

**Comment by Seveler** [comment]
Dear Kylie,
thank you very much for your help! Using `obj@imageData$data[[1]]` worked perfectly to get the intensity matrix.

I realised, that your data is the pre-processed version with 593 m/z values, as written in the paper. I was hoping to get the unprocessed continuous data, as I would like to use your data to demonstrate a new peak-picking algorithm. Would it be possible to publish the unprocessed data?
Thanks in advance!
-Philipp

**Comment by kuwisdelu** [comment]
The bladder TMA dataset is available on PRIDE: https://www.ebi.ac.uk/pride/archive/projects/PXD026459

Questions on that dataset should be directed to Dr. Melanie Föll ([melanie.foell@mol-med.uni-freiburg.de](mailto:melanie.foell@mol-med.uni-freiburg.de).

**Comment by Seveler** [comment]
Many thanks for the hint!
